# Generated by Django 4.1.7 on 2024-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_auth", "0010_parsersetting_excludes_parsersetting_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsersetting",
            name="groups",
            field=models.TextField(blank=True, null=True),
        ),
    ]
