# Generated by Django 4.1.7 on 2024-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_auth", "0011_alter_parsersetting_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsersetting",
            name="groups",
            field=models.TextField(blank=True),
        ),
    ]
