# Generated by Django 4.1.7 on 2024-05-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0008_telegramgroup_users_alter_telegramgroup_city"),
        ("telegram_auth", "0012_alter_parsersetting_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parsersetting",
            name="groups",
        ),
        migrations.AddField(
            model_name="parsersetting",
            name="groups",
            field=models.ManyToManyField(blank=True, to="saite.telegramgroup"),
        ),
    ]
