# Generated by Django 4.1.7 on 2024-05-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_auth", "0013_remove_parsersetting_groups_parsersetting_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parsersetting",
            name="groups",
        ),
        migrations.AddField(
            model_name="parsersetting",
            name="groups",
            field=models.TextField(blank=True),
        ),
    ]
