# Generated by Django 4.1.7 on 2024-05-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0015_remove_telegramgroup_channel_id"),
        ("telegram_auth", "0016_alter_parsersetting_excludes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsersetting",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="saite.city"
            ),
        ),
    ]
