# Generated by Django 4.1.7 on 2024-05-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saite", "0007_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="telegram_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="telegramgroup",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_groups",
                to="saite.city",
            ),
        ),
    ]
