# Generated by Django 4.1.7 on 2024-05-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0008_telegramgroup_users_alter_telegramgroup_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramgroup",
            name="users",
        ),
        migrations.AlterField(
            model_name="telegramgroup",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_groups",
                to="saite.city",
            ),
            preserve_default=False,
        ),
    ]
