# Generated by Django 4.1.7 on 2024-05-28 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saite", "0009_remove_telegramgroup_users_alter_telegramgroup_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="telegramgroup",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_groups",
                to="saite.city",
            ),
        ),
        migrations.CreateModel(
            name="UserTelegramGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saite.telegramgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="telegramgroup",
            name="users",
            field=models.ManyToManyField(
                related_name="custom_groups",
                through="saite.UserTelegramGroup",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
