# Generated by Django 4.1.7 on 2024-05-28 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saite", "0010_telegramgroup_is_custom_alter_telegramgroup_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramgroup",
            name="users",
        ),
        migrations.AlterField(
            model_name="usertelegramgroup",
            name="telegram_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="saite.telegramgroup",
            ),
        ),
        migrations.AlterField(
            model_name="usertelegramgroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_telegram_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
