# Generated by Django 4.1.7 on 2024-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0011_remove_telegramgroup_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramgroup",
            name="channel_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
