# Generated by Django 4.1.7 on 2024-05-28 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0014_remove_telegramgroup_is_custom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramgroup",
            name="channel_id",
        ),
    ]
