# Generated by Django 4.1.7 on 2024-06-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saite", "0015_remove_telegramgroup_channel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=750)),
            ],
        ),
    ]
